<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Title>MonkeyPlayground Client</Title>
        <Authors>Pygmalions</Authors>
        <Description>Client for MonkeyPlayground.</Description>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Polly" Version="8.6.4" />
      <PackageReference Include="RestSharp" Version="112.1.0" />
    </ItemGroup>

</Project>
